# -*- coding: utf-8 -*-
"""Datatypes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ms-U6Wb0OvI93rVaFKFmQyakchKce_vH

#LIST
"""

a=[1,2,3,4,5]
b=["champ",2,'a',16.5,]
print(a,b)
print(len(b))  #Length Of the List
print(b[0])    #Locates element based on Index
print(a[1:])   #Prints element except the 1st
print(a[:2])   #Print elements upto 2nd Index
print(a+b)     #Concates and Prints two lists
a.append(6)    #appends the element at the end of the list
print(a)
b.reverse()    #Reverses the list
print(b)
print(min(a))  #Prints minimum element from a
print(max(a))  #Prints maximum element from a
 
c=[a,b]        #Nested List Matrix
print(c)
print(c[0])    #Printing Row
print(c[0][0]) #Printing 1st Element

"""#Dictionary"""

a={"Name":"Elon", "Surname":"Musk", "Company":["Tesla","SpaceX"], "Age":50}
print(a["Name"])       #Print Element based on Key
print(a["Surname"])    #Print Element based on Key
print(a["Company"])    #Print Element based on Key
a["Age"]=52            #Changing Values
print(a["Age"])
print(a)               #Printing Whole Dictionary

print(a.keys())        #Prints Keys of Dictionary
print(a.values())      #Prints values of Dictionary
print(a.items())        #Prints keys-values of Dictionary

b={"Climate":{"Condition":{"Humidity":"70 Percentage", "Temperature":"40 Degree"}}}     #Nested Dictionary
print(b["Climate"]["Condition"]["Humidity"])

"""#Tuple"""

a=("Champ", 21, 99.5)
print(len(a))
print(a[0])
print(a.index("Champ"))

"""#Sets

"""

a = set()
a.add("Champ")
a.add(12)
a.add(99.5)
print(a)
b = {"Prutha", 99.5, 88, "M"}
print(b)

"""#Boolean"""

a = 5
b = 10
c = 15
print(a>b)
print(a<b)
print(a==b)
print(a!=b)
print(a<=b)
print(a>=b)
print(a<b and c>a)
print(a<b or c>a)