# -*- coding: utf-8 -*-
"""Statements.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ri9lgG9gRSgE2_byDCYLwcfbbeCfKStm

#If-Else Statement
"""

a = True
if a:
  print("Positive")
else:
  print("Negative")

a = 5
b = 10
if a>b:
  print("A is Maximu")
else:
  print("B is Maximum")

"""#ElIf(Else If) Condition"""

a = 5
b = 10
c = 15
if a>b:
  print("a is maximum")
elif c==b:
  print("b is maximum")
  print("c is equals to b")
else:
  print("c is maximum")

"""#For Loop"""

a = [1,2,3,4,5,6,7,8,9,10]
for i in a:
  print(i)
b = [x for x in "Prutha"]
print(b)
for i in a:
  if i%2 == 0:
    print(i,"Even Number")
  else:
    print(i,"Odd Number")
for x in "Hello Prutha":
  print(x)

"""#For Loop With Dictionary"""

a = {"Name":"Elon Musk", "Age":"52", "Company":"Tesla"}
for k,v in a.items():
  print(k)
  print(v)

"""#While"""

a = 0
while a <= 10:
  print(a)
  a+=1 
  if a==5:
    print("a is equals to 5")
    break
  else:
    print("Continueeee")
    continue