# -*- coding: utf-8 -*-
"""Libraries and Modules.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xXsMqj1KaWaJTW6eyOMpjDGxp-RE92uR

#Python Modules and Libraries

#Accessing One Python Program from Another
"""

import main #Importing Python File
main.welcome() #Parenthesis to access a Function
x = main.a #No Parenthesis to access a variable
y = main.b
print(x+y)

"""#Accessing One Python Program from Another present in another folder"""

from sample_data.demo import main
main.welcome() #Parenthesis to access a Function
x = main.a #No Parenthesis to access a variable
y = main.b
print(x+y)

"""#Try Except Finally"""

for i in range(3,-3,-1):
  try:
    print(1.0/i)
  except ZeroDivisionError:
    print("Not Divisible by Zero")





for i in range(3,-3,-1):
  try:
    print(1.0/i)
  except ZeroDivisionError as er:
    print("Not Divisible by Zero Error:", str(er.args[0]))

def check():
  while True:
    try:
      a = int(input("Enter any Number:"))
      b = int(input("Enter any Number:"))
    except:
      print("Enter Correct Numbers")
      continue
    else:
      print("Correct Numbers :(")
      break
    finally:
      print("Perfect :)")
      print(a+b)
check()

"""#Importing Libraries"""

import math #import libraryName

"""#Installing Library"""

!pip install imutils #pip install libraryname (imutils-to make basic image processing functions such as translation, rotation, resizing, skeletonization, displaying Matplotlib images, sorting contours, detecting edges, and much more easier with OpenCV )

"""#Uninstalling Library"""

!pip uninstall imutils

"""#Checking Current Version of imutils"""

!pip install imutils

import imutils
imutils.__version__

"""#Installing Library Based on Version"""

!pip install imutils==0.5.4

"""#Playing With Libraries

#Math Library
"""

import math
print(dir(math))
print(math.pi)

import math as mt
print(dir(mt))
print(mt.pi)

"""#Reduce Function"""

from functools import reduce
lst = [47,11,42,13]
reduce(lambda x,y:x+y,lst) #adds all the elements in list 'lst' and produces the sum of all elements, reduces lines of code

"""#IPython Functions"""

from IPython.display import Image
Image('https://venturebeat.com/wp-content/uploads/2018/09/ironman.jpg')

"""#Filter"""

def check(num):
  if num%2 ==0:
    return True
lst =range(20)
list(filter(check,lst))