# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mDcjwZBDpDtytHcxhoHTbF0Ipv5CRhFr

#Basic Python

##Arithmetic Program
"""

a=5
b=6
c=a+b
print(c)

d=a*b
print(d)

"""#Simple Arithmetic With User Input"""

a=int(input("Enter the value of a:"))
b=int(input("Enter the value of b:"))
add=a+b
sub=a-b
mul=a*b
div=a/b
mod=a%b
print(add)
print(sub)
print(mul)
print(div)
print(mod)

"""######Input("Message")-Used to take User Input.
By Default takes String Input.
To take different input:
Datatype(input("Message"))

#Print Using Format
"""

print("Add: {0}, Sub: {1}, Mul: {2}, Div: {3}, Mod: {4}".format(add,sub,mul,div,mod))

"""#Print Using Padding And Precision"""

print("Add: %d, Sub: %d, Mul: %d, Div: %25.3f, Mod: %d"%(add,sub,mul,div,mod))

"""######here in %25.3f
25-padding it will leave 25 spaces from the text,

3-precision it will print upto 3 decimal digits

#Print Using Padding and Alignment

######'>' - Right Align
'<' - Left Aligh
"""

print('{0:<4} {1:<4} {2:<4} {3:<4}'.format("Add","Sub","Mul","Div","Mod"))
print('{0:<4} {1:<4} {2:<4} {3:<4}'.format(add,sub,mul,div,mod))

"""######0:<4
Here 0 - index,

< - Alignment,

4 - padding.

#Calculate Power(a^b)
"""

a=3
b=3
power=a**b
print(power)