# -*- coding: utf-8 -*-
"""String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14euD0i35CVKeU5xvsA-_n4SWUwJH8cLm

#Strings
"""

a="Python"
b="Bootcamp"
print(a)
print(b)

"""#String Concatenation"""

print(a+b)

"""#Length Of The String"""

print(len(a))

"""#Repeat Characters of String"""

a="S"
b=a*5
print(b)

"""#String Index"""

a="Champ"
print(a[3])    #prints a specific character at the given index
print(a[2:])   #grabbing remaining elements except till the given colon
print(a[:2])   #grabs elements upto the index
print(a[-1])   #grabs last element
print(a[:-1])  #grabs all the elements except the last one
print(a[::2])  #grabs everything with two steps(skips two elements)
print(a[::-1]) #prints the string backwards

"""#String Functions"""

print(a.upper())  #prints string in upper case
print(a.lower())  #prints string in lower case

a="Master Class"
b=a.split()      #splits the string into two elements of an array
print(b)
c="ElonMusk, SteveJobs, ThomasEdison"
d=c.split(",")   #splits string based on delimitir(symbol)
print(d)