# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mDcjwZBDpDtytHcxhoHTbF0Ipv5CRhFr

#Basic Python

##Arithmetic Program
"""

a=5
b=6
c=a+b
print(c)