# -*- coding: utf-8 -*-
"""Miscellaneous.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zYoN-ZywLY0pCBJSRt1hV8inZDXpJXNP

#Counters - Gives the count of the element being repeated for a particular time
"""

from collections import Counter
print(Counter([5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,5,5,5,5,5,6,6,6,6,7,7,7,7,9,3]))   #Numbers
print(Counter('sdasdasdasdasdasdasdasdasdasdasda'))   #String

"""#Regular Expression - RE Library
Helpful for analyzing data and identifying pattern from it.
Pattern Date:
"""

import re
patt = r'\d{2}-\d{2}-\d{4}'
message = "Birthdate is 16-11-1922"
re.findall(patt,message)

"""#Working with Files"""

f = open("welcome.txt","r")
print(f.read())
f.close()

f = open("welcome.txt","r")
print(f.read(5)) #Reading first 5 words
f.close()

f = open("welcome.txt","r")
print(f.readline()) #Reading first 5 words
f.close()

f = open("welcome.txt","r")
for x in f:
  print(x)

"""#File Handling using Pandas 
a Python package providing fast, flexible, and expressive data structures designed to make working with “relational” or “labeled” data both easy and intuitive
"""

!pip install pandas

import pandas as pd
data = pd.read_csv('data.csv')
print(data.to_string())

import pandas as pd
data = pd.read_csv('data.csv')
print(data.shape)  #Prints the number of Rows and Columns in the dataset
print(data.describe())  #Prints the count of data present in Dataset
print(data.head(5)) #Prints the top 5 highest values of Dataset

"""#Working with Directories
OS module provides the facility to establish the interaction between the user and the operating system. It offers many useful OS functions that are used to perform OS-based tasks and get related information about operating system. The OS comes under Python's standard utility modules.
"""

import os
print(os.getcwd())   #Gets the information about current working directory
print(os.listdir())  #List the information of directories present
os.mkdir("Junk")           #Makes a new directory

"""#Shutil Library
 shutil module offers a number of high-level operations on files and collections of files. In particular, functions are provided which support file copying and removal. For operations on individual files, see also the os module. Even the higher-level file copying functions 
"""

import shutil
shutil.move('welcome.txt','/content/Junk')

"""#Send2Trash
Small package that sends files to the Trash (or Recycle Bin) natively and on all platforms
"""

import send2trash
os.listdir()
send2trash.send2trash('Junk/welcome.txt')

os.listdir()

"""#Time Library"""

import time
print(time.time())  #Prints time since epoch

print(time.gmtime()) #TimeinDifferentFormatsLike: Year,Month,Day,Hour,Second,Day.

print(time.ctime())  #Current time

startTime = time.time()
i=0
while(i<5):
  i+=1
  print(".")
  time.sleep(1) #delay 1 second
stopTime = time.time()
diff = stopTime - startTime
diff

"""#DateTime"""

import datetime
x = datetime.datetime.now()
print(x)

import datetime
x = datetime.datetime(2022,11,24,12,00,00)  #(year,month,date,hour,minute,second,microsecond)
print(x)

import datetime
a = datetime.datetime(2022,11,24)
print(a.strftime("%B"))