# -*- coding: utf-8 -*-
"""Functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ZXsWbkYU2SGqNaNT-iHSGGaqJlzrMIW

#Functions

3 Parts of function

1) Defination

2) Declaration

3) Call

# Initialization and Call of a Basic Function:
"""

def welcome():
  print("Call Me! Then I will execute your command!")

welcome()

"""#Parameterized Fuction: """

def welcome(a):
  print("Call me!!! Then I'll execute your command!")
  print(format(a))

welcome("Ohk! You Called!! Command Executed!!")

"""# Return Values"""

def add(a,b):
  add = a + b
  print(add)

add(80,44)

def addR(a,b):
  add = a + b
  return add

addR(45,5)