# -*- coding: utf-8 -*-
"""Lambda-Args-Kwargs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v1HSLly43dwwIrI1kNHzDwoo4DdrSsUw

#Lambda Function

Creating Anoynomous Function without using DEF keyword
"""

cubefn = lambda num: num**3
cubefn(6)

"""#Args And Kwargs
Args - Allows to put any number of Arguements in a function without predefining them.

Kwargs - Key-Value Pair Arguements can be added wothout predefining them.
"""

def addR(*argg):
  return sum(argg)
addR(10,20,30,40,50,60,70,80,90,100)

from traitlets.traitlets import inspect
def func(**kwargs):
  if 'name' in kwargs:
    print("My Name is {0}".format(kwargs['name']))
  if 'age'  in kwargs:
    print("And Age is {0}".format(kwargs['age']))
  else:
    print("No Keyword Found")
func(name="Prutha",age="22")