# -*- coding: utf-8 -*-
"""Project-Prime-Number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NSl-tKvJTtzB5uYgtoyaCLrHlwP0rzgu
"""

def check(numbers):
  primenumber = []
  for number in numbers:
    if number>1:
      for i in range(2, int(number/2)+1):
        if(number % i) == 0:
          print(number, "is not a prime number")
          break
        else:
          print(number, "is a prime number")
          primenumber.append(number)
      else:
        pass
    return primenumber

check([2,3,4,5,6,7,8,9])

"""**check()** -  is a fucntion that checks whether the number is prime or not!

**primenumber** is an empty array where we will append only prime numbers

**first for loop** will traverse through numbers that we pass as arguement while calling the function

the **first if condition** will check whether the number is greater than 1

the **second for loop** is to traverse for the numbers that are between 2 to 
any number that is divisible by 2 and is  + 1

the **second if statement** checks if the number divisible by any number in the array, is 0 then its not a prime number

the **first else condition** means the above condition is wrong which means the number is prime and **appends it to the primenumber** array.

the **second else condition** fulfills if the number is not greater than 1.

the **return statement** returns the prime number array
"""