# -*- coding: utf-8 -*-
"""Range-Enumerate-Zip-Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JvgpzjjGtb0bzGxZADXUFt1kU_XyJZfL

#Range Function
"""

for a in range(5):          #Prints a specific range
  print(a)
for b in range(0,10,2):     #Prints a specific range by jumping specific locations in Increment
  print(b)
for c in range(10, 1, -2):  #Prints a specific range by jumping specific locations in Decremet
  print(c)

"""#Ennumerate Function
######Tracks Number of Iteration without incrementing the iteration
"""

a = 0
for i,a in enumerate("Hello Prutha"):
  print(i,a)

"""#Zip
######Creating a tuple by zipping 2 lists
"""

a = ["Name", "Age", "Hobby"]
b = ["Prutha", "22", "Coding"]
list(zip(a,b))